FROM python:3.6-buster

MAINTAINER Azam <kazam1920@gmail.com>

WORKDIR /app

COPY . /app

RUN python3.6 -m pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

